#pragma config(Sensor, S1,     SonarL,         sensorSONAR)
#pragma config(Sensor, S2,     SonarR,         sensorSONAR)
#pragma config(Sensor, S4,     IrLink,         sensorI2CCustom)
#pragma config(Motor,  motorA,          chooch,        tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "drivers/hitechnic-irlink.h"

const int RIGHT_TIES = 16;
const int CENTER_TIES = 9;
const int LEFT_TIES = 15;
const int MOTOR_POWER = 5;
const float SAFTEY_MARGIN_RIGHT = 0.17;
const float SAFTEY_MARGIN_LEFT = 0.25;
const short DIR_RIGHT = -1;
const short DIR_LEFT = 1;

bool trainPresent(int sensor_num){
	return SensorValue[sensor_num] == 255 || SensorValue[sensor_num] < 20;
}

int msToTraverseTies(int ms_between_sensors, int num_ties){
	int ms_per_tie = ms_between_sensors / CENTER_TIES;
	return (num_ties * ms_per_tie);
}

void moveChooch(short direction){
	PFMotor(pfmotor_S4_C2_A, (ePWMMotorCommand)(direction * MOTOR_POWER));
}

task main()
{
	moveChooch(DIR_RIGHT);
	while(!trainPresent(SonarR)) wait1Msec(1);
	wait1Msec(2500);
	moveChooch(DIR_LEFT);

	int ms_between_sensors;

	while (true){
		ms_between_sensors = 0;
		while(!trainPresent(SonarR)) wait1Msec(1);
		//PlaySound(soundBlip);

		while(!trainPresent(SonarL)){
			wait1Msec(1);
			ms_between_sensors += 1;
		}
		//PlaySound(soundBlip);

		wait1Msec(msToTraverseTies(ms_between_sensors, LEFT_TIES) * (1.0 - SAFTEY_MARGIN_LEFT));
		moveChooch(DIR_RIGHT);

		ms_between_sensors = 0;

		while(!trainPresent(SonarL)) wait1Msec(1);
		//PlaySound(soundBlip);

		while(!trainPresent(SonarR)){
			wait1Msec(1);
			ms_between_sensors += 1;
		}
		//PlaySound(soundBlip);

		wait1Msec(msToTraverseTies(ms_between_sensors, RIGHT_TIES)* (1.0 - SAFTEY_MARGIN_RIGHT));
		moveChooch(DIR_LEFT);
	}
}
