#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          elbow,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          shoulder,      tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rotate,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void yeet(){
	nMotorEncoderTarget[motorB] = 120;
	nMotorEncoderTarget[motorA] = -45;
	motor[motorB] = -100;
	motor[motorA] = 100;
	wait10Msec(9);

	nMotorEncoderTarget[motorA] = 50;
	motor[motorA] = -100;

	wait10Msec(40);
	motor[motorB] = 0;
	motor[motorA] = 0;
}

task main()
{
	bool pressed = false;
	while (true){
		if (!pressed && SensorValue(touchSensor)){
			yeet();
			pressed = true;
		} else {
			pressed = SensorValue(touchSensor);
		}
	}
}
